// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EM_algorithm_censored_arma
DataFrame EM_algorithm_censored_arma(arma::vec data, double ind, arma::vec d, DataFrame parameter_starts, int N);
RcppExport SEXP _hSSALT_EM_algorithm_censored_arma(SEXP dataSEXP, SEXP indSEXP, SEXP dSEXP, SEXP parameter_startsSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type ind(indSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type parameter_starts(parameter_startsSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(EM_algorithm_censored_arma(data, ind, d, parameter_starts, N));
    return rcpp_result_gen;
END_RCPP
}
// EM_algorithm_interval_arma
DataFrame EM_algorithm_interval_arma(arma::vec data, double delta, double ind, arma::vec d, DataFrame parameter_starts, double q2, int N);
RcppExport SEXP _hSSALT_EM_algorithm_interval_arma(SEXP dataSEXP, SEXP deltaSEXP, SEXP indSEXP, SEXP dSEXP, SEXP parameter_startsSEXP, SEXP q2SEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type ind(indSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type parameter_starts(parameter_startsSEXP);
    Rcpp::traits::input_parameter< double >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(EM_algorithm_interval_arma(data, delta, ind, d, parameter_starts, q2, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hSSALT_EM_algorithm_censored_arma", (DL_FUNC) &_hSSALT_EM_algorithm_censored_arma, 5},
    {"_hSSALT_EM_algorithm_interval_arma", (DL_FUNC) &_hSSALT_EM_algorithm_interval_arma, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_hSSALT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
