# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EM_algorithm_censored_arma <- function(data, ind, d, parameter_starts, N, tol) {
    .Call('_hSSALT_EM_algorithm_censored_arma', PACKAGE = 'hSSALT', data, ind, d, parameter_starts, N, tol)
}

EM_algorithm_interval_arma <- function(data, delta, ind, d, parameter_starts, q2, N, tol) {
    .Call('_hSSALT_EM_algorithm_interval_arma', PACKAGE = 'hSSALT', data, delta, ind, d, parameter_starts, q2, N, tol)
}

